[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[[bin]]
name = "guess_number_game"
